version: '3.7'

services:
  postgraphile:
    container_name: ${COMPOSE_PROJECT_NAME}_${SERVICE_NAME}
    restart: ${DOCKER_RESTART_POLICY}
    image: ${DOCKER_IMAGE_REGISTRY:-}${APP_PREFIX}/${SERVICE_NAME}:${APP_VERSION}
    build:
      context: ./
      args:
        - DOCKER_BASE_IMAGE
        - NODE_ENV
    init: true
    cap_drop:
      - ALL
    env_file:
      - ${DOCKER_GENERATED_ENV_FILE:-./env/defaults}
    networks:
      backend:
        aliases:
          - ${SERVICE_NAME}
      frontend:
        aliases:
          - ${SERVICE_NAME}
    deploy:
      replicas: ${POSTGRAPHILE_REPLICAS}
    logging:
      driver: ${DOCKER_LOGGING_DRIVER}
      options:
        max-file: ${DOCKER_LOGGING_MAX_FILE}
        max-size: ${DOCKER_LOGGING_MAX_SIZE}
    labels:
      - traefik.enable=${PROXY_ROUTER_ENABLE}
      - traefik.docker.network=${DOCKER_FRONTEND_NETWORK_NAME}

      - traefik.http.routers.${APP_PREFIX}-${SERVICE_NAME}-host.rule=HostRegexp(`${SERVICE_NAME}.${APP_PREFIX}.${PROXY_ROUTER_DOMAIN}`)
      - traefik.http.routers.${APP_PREFIX}-${SERVICE_NAME}-path.rule=PathPrefix(`/${APP_PREFIX}/${SERVICE_NAME}`)

      - traefik.http.services.${APP_PREFIX}-${SERVICE_NAME}.loadbalancer.server.port=${DEFAULT_HTTP_PORT}

      - traefik.http.middlewares.${APP_PREFIX}-${SERVICE_NAME}-ratelimit.ratelimit.burst=${POSTGRAPHILE_RATE_LIMIT_BURST}
      - traefik.http.middlewares.${APP_PREFIX}-${SERVICE_NAME}-ratelimit.ratelimit.average=${POSTGRAPHILE_RATE_LIMIT_AVERAGE}
      - traefik.http.middlewares.${APP_PREFIX}-${SERVICE_NAME}-ratelimit.ratelimit.period=${POSTGRAPHILE_RATE_LIMIT_PERIOD}
      - traefik.http.middlewares.${APP_PREFIX}-${SERVICE_NAME}-compress.compress=true
      - traefik.http.middlewares.${APP_PREFIX}-${SERVICE_NAME}-stripprefix.stripprefix.prefixes=/${APP_PREFIX}/${SERVICE_NAME}

      - traefik.http.middlewares.${APP_PREFIX}-${SERVICE_NAME}-middlewares-path.chain.middlewares=${APP_PREFIX}-${SERVICE_NAME}-ratelimit, ${APP_PREFIX}-${SERVICE_NAME}-compress, ${APP_PREFIX}-${SERVICE_NAME}-stripprefix
      - traefik.http.routers.${APP_PREFIX}-${SERVICE_NAME}-path.middlewares=${APP_PREFIX}-${SERVICE_NAME}-middlewares-path

      - traefik.http.middlewares.${APP_PREFIX}-${SERVICE_NAME}-middlewares-host.chain.middlewares=${APP_PREFIX}-${SERVICE_NAME}-ratelimit, ${APP_PREFIX}-${SERVICE_NAME}-compress
      - traefik.http.routers.${APP_PREFIX}-${SERVICE_NAME}-host.middlewares=${APP_PREFIX}-${SERVICE_NAME}-middlewares-host

networks:
  backend:
    name: ${APP_PREFIX}_${DOCKER_BACKEND_NETWORK_NAME}
    external: true
  frontend:
    name: ${DOCKER_FRONTEND_NETWORK_NAME}
    external: true

